FROM rust:latest AS builder
WORKDIR /build
COPY shim/ ./
RUN cargo build --release

FROM ubuntu:latest

RUN apt update && apt upgrade -y

RUN apt install -y \
    bison \
    cmake \
    curl \
    flex \
    g++ \
    gdb-multiarch \
    git \
    make \
    ninja-build \
    pkg-config \
    python3 \
    python3-pip \
    python3-venv \
    ripgrep \
    tree \
    wget \
    xxd \
    xz-utils \
    zsh

COPY --from=builder /build/target/release/shim /usr/local/bin/shim
